# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Victor Bellon - Resume
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
name: Víctor Bellón
tagline: Machine Learning
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
style: styles-7
#sidebar links
email: vbellonbcn@gmail.com
#website: blog.webjeda.com #do not add http://
linkedin: víctor-manuel-bellón-molina-79814328
github: vmolina
twitter: '@aldagrim'
